[project]
name = "ayalite"
version = "0.1.0"
description = "Discord bot for Twitch notifications"
readme = "README.md"
authors = [
    { name = "shiki", email = "shiki@shikiwoo.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "discord-py>=2.7.1",
    "python-dotenv>=1.2.2",
    "twitch-py>=4.0.4",
]

[project.scripts]
ayalite = "ayalite:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "standard"
